my:
  greeting: Hello World from config server updated
  list:
    values: Apple, Banana, Orange, Cherry
 
db:
  connection: conntention-string-from-config-server-updated
  host: 127.0.0.32
  port: 44445
